import React from "react"
import { DashboardLayout } from "./dashboard-layout"
import { Button } from "./ui/button"
import { Card } from "./ui/card"
import { Input } from "./ui/input"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "./ui/table"
import { Download, Eye, Search } from "lucide-react"
import { Badge } from "./ui/badge"

const generatedCertificates = [
  {
    id: "CS101",
    studentName: "John Doe",
    certificateType: "Bonafied Certificate",
    dateGenerated: "2023-04-15",
    generatedBy: "Dr. Smith",
  },
  {
    id: "CS102",
    studentName: "Jane Smith",
    certificateType: "Scholarship",
    dateGenerated: "2023-04-14",
    generatedBy: "Dr. Johnson",
  },
  {
    id: "CS103",
    studentName: "Mike Johnson",
    certificateType: "Bonafied Certificate",
    dateGenerated: "2023-04-13",
    generatedBy: "Prof. Williams",
  },
  {
    id: "CS104",
    studentName: "Sarah Williams",
    certificateType: "Scholarship",
    dateGenerated: "2023-04-12",
    generatedBy: "Dr. Smith",
  },
]

export function GeneratedCertificatesPage() {
  return (
    <DashboardLayout>
      <div className="flex flex-col gap-6">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-3xl font-bold tracking-tight">Generated Certificates</h2>
            <p className="text-muted-foreground">View and download generated certificates</p>
          </div>
          <Button className="bg-[#4a2639] hover:bg-[#4a2639]/90 text-white">
            <Download className="mr-2 h-4 w-4" />
            Export All
          </Button>
        </div>

        <div className="flex items-center gap-4">
          <div className="relative flex-1 max-w-sm">
            <Search className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
            <Input type="search" placeholder="Search certificates..." className="pl-8" />
          </div>
          <Button variant="outline">Filter</Button>
        </div>

        <Card className="border-[#4a2639]/20">
          <div className="p-6">
            <div className="rounded-md border">
              <Table>
                <TableHeader className="bg-[#4a2639]">
                  <TableRow>
                    <TableHead className="text-[#ffe2f3]">Roll No</TableHead>
                    <TableHead className="text-[#ffe2f3]">Name</TableHead>
                    <TableHead className="text-[#ffe2f3]">Type</TableHead>
                    <TableHead className="text-[#ffe2f3]">Date Generated</TableHead>
                    <TableHead className="text-[#ffe2f3]">Generated By</TableHead>
                    <TableHead className="text-right text-[#ffe2f3]">Action</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {generatedCertificates.map((certificate) => (
                    <TableRow key={certificate.id}>
                      <TableCell className="font-medium">{certificate.id}</TableCell>
                      <TableCell>{certificate.studentName}</TableCell>
                      <TableCell>
                        <Badge variant="outline" className="bg-pink-100 text-[#4a2639] border-0">
                          {certificate.certificateType}
                        </Badge>
                      </TableCell>
                      <TableCell>{certificate.dateGenerated}</TableCell>
                      <TableCell>{certificate.generatedBy}</TableCell>
                      <TableCell className="text-right">
                        <div className="flex justify-end gap-2">
                          <Button size="icon" variant="outline" className="h-8 w-8">
                            <Eye className="h-4 w-4" />
                            <span className="sr-only">View</span>
                          </Button>
                          <Button size="icon" variant="outline" className="h-8 w-8">
                            <Download className="h-4 w-4" />
                            <span className="sr-only">Download</span>
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
          </div>
        </Card>
      </div>
    </DashboardLayout>
  )
}
